//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  at least one  ähnelt.
        /// </summary>
        internal static string AtLeast {
            get {
                return ResourceManager.GetString("AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Since the option &quot;Show Possible Values&quot; is enabled, candidates are not shown. Disable option &quot;Show Possible Values&quot;? ähnelt.
        /// </summary>
        internal static string CandidatesNotShown {
            get {
                return ResourceManager.GetString("CandidatesNotShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data for Cell in row {0}, column {1}{2}: ähnelt.
        /// </summary>
        internal static string Cellinfo {
            get {
                return ResourceManager.GetString("Cellinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value:  ähnelt.
        /// </summary>
        internal static string CellValue {
            get {
                return ResourceManager.GetString("CellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking... ähnelt.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passes so far: {0:n0} ähnelt.
        /// </summary>
        internal static string CheckingStatus {
            get {
                return ResourceManager.GetString("CheckingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem ({0}Sudoku) has{1}solution. ähnelt.
        /// </summary>
        internal static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die classic  ähnelt.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Candidates ähnelt.
        /// </summary>
        internal static string ClearCandidates {
            get {
                return ResourceManager.GetString("ClearCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Content ähnelt.
        /// </summary>
        internal static string ClearContent {
            get {
                return ResourceManager.GetString("ClearContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current problem was modified but could not be saved since it is invalid. Close anyway? ähnelt.
        /// </summary>
        internal static string CloseAnyway {
            get {
                return ResourceManager.GetString("CloseAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complexity Level:  ähnelt.
        /// </summary>
        internal static string ComplexityLevel {
            get {
                return ResourceManager.GetString("ComplexityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Congratulations! ähnelt.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory {0} could not be created, Booklet problems will not be saved! ähnelt.
        /// </summary>
        internal static string CreateDirectoryFailed {
            get {
                return ResourceManager.GetString("CreateDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal problem ({0}): {1} values\nChecking problem: {2} values ähnelt.
        /// </summary>
        internal static string CurrentMinimalProblem {
            get {
                return ResourceManager.GetString("CurrentMinimalProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definite Cells: ähnelt.
        /// </summary>
        internal static string DefiniteCells {
            get {
                return ResourceManager.GetString("DefiniteCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definite Value:  ähnelt.
        /// </summary>
        internal static string DefiniteValue {
            get {
                return ResourceManager.GetString("DefiniteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sudoku Solver and Generator\nSupports both classic 9*9 Sudokus and X-Sudokus ähnelt.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap digitCandidates {
            get {
                object obj = ResourceManager.GetObject("digitCandidates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct Blocks:  ähnelt.
        /// </summary>
        internal static string DirectBlocks {
            get {
                return ResourceManager.GetString("DirectBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sudoku (Solution #{0}, {1:n0} passes) ähnelt.
        /// </summary>
        internal static string DisplaySolution {
            get {
                return ResourceManager.GetString("DisplaySolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easy ähnelt.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter all given values (e.g., from a problem of your newspaper) and than click on &quot;Problem|Start Game&quot;. ähnelt.
        /// </summary>
        internal static string EnterValues {
            get {
                return ResourceManager.GetString("EnterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export of Problem as HTML is not possible! ähnelt.
        /// </summary>
        internal static string ExportNotPossible {
            get {
                return ResourceManager.GetString("ExportNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original Problem saved as: ähnelt.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filled Cells:  ähnelt.
        /// </summary>
        internal static string FilledCells {
            get {
                return ResourceManager.GetString("FilledCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sudoku Problems (*{0}) | *{0} ähnelt.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Problems generated so far: {0} (of {1}) ähnelt.
        /// </summary>
        internal static string GeneratedProblems {
            get {
                return ResourceManager.GetString("GeneratedProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating... ähnelt.
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems analyzed so far: {0:n0} ähnelt.
        /// </summary>
        internal static string GeneratingStatus {
            get {
                return ResourceManager.GetString("GeneratingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generation aborted!\n{0}Problems analyzed so far: {1:n0}\nPasses done so far: {2:n0} ähnelt.
        /// </summary>
        internal static string GenerationAborted {
            get {
                return ResourceManager.GetString("GenerationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard ähnelt.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://sudoku.pi-c-it.de/index.php/en/ ähnelt.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;de&quot; lang=&quot;de&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;&lt;meta name=&quot;robots&quot; content=&quot;index, follow&quot; /&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Sudoku, pi-c-it&quot; /&gt;&lt;link rel=&quot;home&quot; type=&quot;text/html&quot; title=&quot;home:pi-c-it&quot; href=&quot;https://www.pi-c-it.de&quot; /&gt;&lt;link rel=&quot;author&quot; title=&quot;Contact&quot; href=&quot;mailto:kontakt%40pi-c-it.de?subject=p [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HTMLFrame {
            get {
                return ResourceManager.GetString("HTMLFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;table class=&quot;grid&quot;&gt;&lt;tr class=&quot;grid&quot;&gt;&lt;td class=&quot;normal&quot;&gt;{00}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{01}&lt;/td&gt;&lt;td class=&quot;rightedge&quot;&gt;{02}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{03}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{04}&lt;/td&gt;&lt;td class=&quot;rightedge dark&quot;&gt;{05}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{06}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{07}&lt;/td&gt;&lt;td class=&quot;rightedge&quot;&gt;{08}&lt;/td&gt;&lt;/tr&gt;&lt;tr class=&quot;grid&quot;&gt;&lt;td class=&quot;normal&quot;&gt;{09}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{10}&lt;/td&gt;&lt;td class=&quot;rightedge&quot;&gt;{11}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{12}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{13}&lt;/td&gt;&lt;td class=&quot;rightedge dar [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HTMLTemplate {
            get {
                return ResourceManager.GetString("HTMLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;table class=&quot;grid&quot;&gt;&lt;tr class=&quot;grid&quot;&gt;&lt;td class=&quot;normal lightdark&quot;&gt;{00}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{01}&lt;/td&gt;&lt;td class=&quot;rightedge&quot;&gt;{02}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{03}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{04}&lt;/td&gt;&lt;td class=&quot;rightedge dark&quot;&gt;{05}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{06}&lt;/td&gt;&lt;td class=&quot;normal&quot;&gt;{07}&lt;/td&gt;&lt;td class=&quot;rightedge lightdark&quot;&gt;{08}&lt;/td&gt;&lt;/tr&gt;&lt;tr class=&quot;grid&quot;&gt;&lt;td class=&quot;normal&quot;&gt;{09}&lt;/td&gt;&lt;td class=&quot;normal lightdark&quot;&gt;{10}&lt;/td&gt;&lt;td class=&quot;rightedge&quot;&gt;{11}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{12}&lt;/td&gt;&lt;td class=&quot;normal dark&quot;&gt;{13 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HTMLTemplateX {
            get {
                return ResourceManager.GetString("HTMLTemplateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of incorrect tries:  ähnelt.
        /// </summary>
        internal static string IncorrectTries {
            get {
                return ResourceManager.GetString("IncorrectTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional indirect Blocks:  ähnelt.
        /// </summary>
        internal static string IndirectBlocks {
            get {
                return ResourceManager.GetString("IndirectBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intermediate ähnelt.
        /// </summary>
        internal static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interrupt!\nTime past: {0}\nPasses made: {1:n0} ähnelt.
        /// </summary>
        internal static string Interrupt {
            get {
                return ResourceManager.GetString("Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Display Language selected! ähnelt.
        /// </summary>
        internal static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must enter a number in row {0}, column {1}. ähnelt.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Problem ähnelt.
        /// </summary>
        internal static string InvalidProblem {
            get {
                return ResourceManager.GetString("InvalidProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper size too small for selected print size. ähnelt.
        /// </summary>
        internal static string InvalidSize {
            get {
                return ResourceManager.GetString("InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} does not contain a valid Sudoku-Problem ähnelt.
        /// </summary>
        internal static string InvalidSudokuFile {
            get {
                return ResourceManager.GetString("InvalidSudokuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file neither contains a classic 9*9-Sudoku nor a X-Sudoku ähnelt.
        /// </summary>
        internal static string InvalidSudokuIdentifier {
            get {
                return ResourceManager.GetString("InvalidSudokuIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value {0} in row {1}, column {2} leads to an invalid problem. ähnelt.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading problem from sudoku.pi-c-it.de... ähnelt.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Sudoku Problems... ähnelt.
        /// </summary>
        internal static string LoadingFiles {
            get {
                return ResourceManager.GetString("LoadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Problem # ähnelt.
        /// </summary>
        internal static string LoadingProblem {
            get {
                return ResourceManager.GetString("LoadingProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem not resolvable. Minimization not possible. ähnelt.
        /// </summary>
        internal static string MinimizationNotPossible {
            get {
                return ResourceManager.GetString("MinimizationNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} pre-allocated values removed ähnelt.
        /// </summary>
        internal static string Minimized {
            get {
                return ResourceManager.GetString("Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimizing... ähnelt.
        /// </summary>
        internal static string Minimizing {
            get {
                return ResourceManager.GetString("Minimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than one Solution! ähnelt.
        /// </summary>
        internal static string MoreThanOne {
            get {
                return ResourceManager.GetString("MoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passes needed:  ähnelt.
        /// </summary>
        internal static string NeededPasses {
            get {
                return ResourceManager.GetString("NeededPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time needed: {0:0#}:{1:0#}:{2:0#},{3:0#} ähnelt.
        /// </summary>
        internal static string NeededTime {
            get {
                return ResourceManager.GetString("NeededTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Problem generated! ({0})\nProblem has {1:n0} pre-allocated cells\nProblems analyzed: {2:n0}\nPasses needed: {3:n0} ähnelt.
        /// </summary>
        internal static string NewProblemGenerated {
            get {
                return ResourceManager.GetString("NewProblemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} new Problems generated, now printing... ähnelt.
        /// </summary>
        internal static string NewProblems {
            get {
                return ResourceManager.GetString("NewProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  no  ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem has no definite cells ähnelt.
        /// </summary>
        internal static string NoHints {
            get {
                return ResourceManager.GetString("NoHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No further minimization possible ähnelt.
        /// </summary>
        internal static string NoMinimizationPossible {
            get {
                return ResourceManager.GetString("NoMinimizationPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die none ähnelt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Problems for printout found ähnelt.
        /// </summary>
        internal static string NoProblems {
            get {
                return ResourceManager.GetString("NoProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  not  ähnelt.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Since the current problem is not solvable it cannot be fixed ähnelt.
        /// </summary>
        internal static string NotFixable {
            get {
                return ResourceManager.GetString("NotFixable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem could not be printed: ähnelt.
        /// </summary>
        internal static string NotPrinted {
            get {
                return ResourceManager.GetString("NotPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem is not resolvable! ähnelt.
        /// </summary>
        internal static string NotResolvable {
            get {
                return ResourceManager.GetString("NotResolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one of the generated problems  ähnelt.
        /// </summary>
        internal static string OneOrMoreProblems {
            get {
                return ResourceManager.GetString("OneOrMoreProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The generated problem  ähnelt.
        /// </summary>
        internal static string OneProblem {
            get {
                return ResourceManager.GetString("OneProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Failed! ähnelt.
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must enter a number between 1 and {0} in row {1}, column {2}. ähnelt.
        /// </summary>
        internal static string OutOfBounds {
            get {
                return ResourceManager.GetString("OutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page  ähnelt.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  (paused) ähnelt.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paused!\n\nClick to continue! ähnelt.
        /// </summary>
        internal static string PausedMessage {
            get {
                return ResourceManager.GetString("PausedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IT Consulting &amp;&amp; Development ähnelt.
        /// </summary>
        internal static string picit {
            get {
                return ResourceManager.GetString("picit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s ähnelt.
        /// </summary>
        internal static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pre-Allocations:  ähnelt.
        /// </summary>
        internal static string PreAllocatedValues {
            get {
                return ResourceManager.GetString("PreAllocatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print candidates instead of the possible values? ähnelt.
        /// </summary>
        internal static string PrintCandidates {
            get {
                return ResourceManager.GetString("PrintCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printing the Problem is not possible! ähnelt.
        /// </summary>
        internal static string PrintNotPossible {
            get {
                return ResourceManager.GetString("PrintNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #{0} ähnelt.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem has\n{0} pre-allocated cells,\n{1} computed cells,\n{2} cells remaining ähnelt.
        /// </summary>
        internal static string ProblemInfo {
            get {
                return ResourceManager.GetString("ProblemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem not solved correctly! ähnelt.
        /// </summary>
        internal static string ProblemNotSolved {
            get {
                return ResourceManager.GetString("ProblemNotSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem loaded ähnelt.
        /// </summary>
        internal static string ProblemRetrieved {
            get {
                return ResourceManager.GetString("ProblemRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems loaded: {0} of {1} ähnelt.
        /// </summary>
        internal static string ProblemsLoaded {
            get {
                return ResourceManager.GetString("ProblemsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem solved! ähnelt.
        /// </summary>
        internal static string ProblemSolved {
            get {
                return ResourceManager.GetString("ProblemSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is extremely tricky. Do you want to publish it on the Sudoku-Homepage? ähnelt.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publishing of the tricky problems failed. Please, save and email them to {0}. Thank You! ähnelt.
        /// </summary>
        internal static string PublishFailed {
            get {
                return ResourceManager.GetString("PublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Very Tricky Problems published. Thank You! ähnelt.
        /// </summary>
        internal static string PublishOK {
            get {
                return ResourceManager.GetString("PublishOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Only ähnelt.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Resources_de_DE {
            get {
                return ResourceManager.GetString("Resources_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Resources_de_DE_Designer {
            get {
                return ResourceManager.GetString("Resources_de_DE_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Problem... ähnelt.
        /// </summary>
        internal static string RetrieveProblem {
            get {
                return ResourceManager.GetString("RetrieveProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save failed! ähnelt.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save of Problem is not possible! ähnelt.
        /// </summary>
        internal static string SaveNotPossible {
            get {
                return ResourceManager.GetString("SaveNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least on severity level must be selected! ähnelt.
        /// </summary>
        internal static string SeverityLevelError {
            get {
                return ResourceManager.GetString("SeverityLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution ähnelt.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution #1 ähnelt.
        /// </summary>
        internal static string SolutionOne {
            get {
                return ResourceManager.GetString("SolutionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution{0} found! ähnelt.
        /// </summary>
        internal static string SolutionsFound {
            get {
                return ResourceManager.GetString("SolutionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solutions so far: {0:n0} ähnelt.
        /// </summary>
        internal static string SolutionsSoFar {
            get {
                return ResourceManager.GetString("SolutionsSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time elapsed:  ähnelt.
        /// </summary>
        internal static string SolutionTime {
            get {
                return ResourceManager.GetString("SolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sudoku Error ähnelt.
        /// </summary>
        internal static string SudokuError {
            get {
                return ResourceManager.GetString("SudokuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today&apos;s Sudoku of The Day is {0} ähnelt.
        /// </summary>
        internal static string SudokuOfTheDayInfo {
            get {
                return ResourceManager.GetString("SudokuOfTheDayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry. Sudoku of the Day could not be loaded ähnelt.
        /// </summary>
        internal static string SudokuOfTheDayNotLoaded {
            get {
                return ResourceManager.GetString("SudokuOfTheDayNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SudokuProblem {
            get {
                object obj = ResourceManager.GetObject("SudokuProblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one type must be selected! ähnelt.
        /// </summary>
        internal static string SudokuTypeError {
            get {
                return ResourceManager.GetString("SudokuTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thinking... ähnelt.
        /// </summary>
        internal static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time so far:  ähnelt.
        /// </summary>
        internal static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Needed:  ähnelt.
        /// </summary>
        internal static string TimeNeeded {
            get {
                return ResourceManager.GetString("TimeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Resolvable! ähnelt.
        /// </summary>
        internal static string TitleNotResolvable {
            get {
                return ResourceManager.GetString("TitleNotResolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Number of Solutions:  ähnelt.
        /// </summary>
        internal static string TotalNumberOfSolutions {
            get {
                return ResourceManager.GetString("TotalNumberOfSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Number of Solutions so far:  ähnelt.
        /// </summary>
        internal static string TotalNumberOfSolutionsSoFar {
            get {
                return ResourceManager.GetString("TotalNumberOfSolutionsSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trivial ähnelt.
        /// </summary>
        internal static string Trivial {
            get {
                return ResourceManager.GetString("Trivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not a valid problem. problem cannot be twittered ähnelt.
        /// </summary>
        internal static string TwitterNotPossible {
            get {
                return ResourceManager.GetString("TwitterNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %40CPichl%20Great%20%23{0}Sudoku%20Problem:%20{1}&amp;url=https://sudoku.pi-c-it.de ähnelt.
        /// </summary>
        internal static string TwitterText {
            get {
                return ResourceManager.GetString("TwitterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://twitter.com/intent/tweet?text= ähnelt.
        /// </summary>
        internal static string TwitterURL {
            get {
                return ResourceManager.GetString("TwitterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Error ähnelt.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current problem has unsaved changes. Do you want to save it? ähnelt.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem is a formal valid {0}Sudoku. ähnelt.
        /// </summary>
        internal static string ValidationStatus {
            get {
                return ResourceManager.GetString("ValidationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version  ähnelt.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://sudoku.pi-c-it.de/index.php/en/version-history ähnelt.
        /// </summary>
        internal static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watchHandCandidates {
            get {
                object obj = ResourceManager.GetObject("watchHandCandidates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
