//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Sudoku.Resources.get_ResourceManager():System.Resources.ResourceManager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Sudoku.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Sudoku.Resources.set_Culture(System.Globalization.CultureInfo):Void")]

namespace Sudoku {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at least one .
        /// </summary>
        internal static string AtLeast {
            get {
                return ResourceManager.GetString("AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes so far: {0:n0}.
        /// </summary>
        internal static string CheckingStatus {
            get {
                return ResourceManager.GetString("CheckingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem has{0}solution..
        /// </summary>
        internal static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity Level: .
        /// </summary>
        internal static string ComplexityLevel {
            get {
                return ResourceManager.GetString("ComplexityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} could not be created, Booklet problems will not be saved!.
        /// </summary>
        internal static string CreateDirectoryFailed {
            get {
                return ResourceManager.GetString("CreateDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definite Cells:.
        /// </summary>
        internal static string DefiniteCells {
            get {
                return ResourceManager.GetString("DefiniteCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku (Solution #{0}, {1:n0} passes).
        /// </summary>
        internal static string DisplaySolution {
            get {
                return ResourceManager.GetString("DisplaySolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Problem saved as:.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Cells: .
        /// </summary>
        internal static string FilledCells {
            get {
                return ResourceManager.GetString("FilledCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Problems (*{0}) | *{0}.
        /// </summary>
        internal static string FilterString {
            get {
                return ResourceManager.GetString("FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Problems generated so far: {0} (of {1}).
        /// </summary>
        internal static string GeneratedProblems {
            get {
                return ResourceManager.GetString("GeneratedProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems analyzed so far: {0:n0}.
        /// </summary>
        internal static string GeneratingStatus {
            get {
                return ResourceManager.GetString("GeneratingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation aborted!\n{0}Problems analyzed so far: {1:n0}\nPasses done so far: {2:n0}.
        /// </summary>
        internal static string GenerationAborted {
            get {
                return ResourceManager.GetString("GenerationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        internal static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt!\nTime past: {0}\nPasses made: {1:n0}.
        /// </summary>
        internal static string Interrupt {
            get {
                return ResourceManager.GetString("Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Language selected!.
        /// </summary>
        internal static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a number in row {0}, column {1}..
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Problem.
        /// </summary>
        internal static string InvalidProblem {
            get {
                return ResourceManager.GetString("InvalidProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} in row {1}, column {2} leads to an invalid problem..
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Sudoku Problems....
        /// </summary>
        internal static string LoadingFiles {
            get {
                return ResourceManager.GetString("LoadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Solution!.
        /// </summary>
        internal static string MoreThanOne {
            get {
                return ResourceManager.GetString("MoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes needed: .
        /// </summary>
        internal static string NeededPasses {
            get {
                return ResourceManager.GetString("NeededPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time used: .
        /// </summary>
        internal static string NeededTime {
            get {
                return ResourceManager.GetString("NeededTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Problem generated! ({0})\nProblem has {1:n0} pre-allocated cells\nProblems analyzed: {2:n0}\nPasses needed: {3:n0}.
        /// </summary>
        internal static string NewProblemGenerated {
            get {
                return ResourceManager.GetString("NewProblemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new Problems generated, now printing....
        /// </summary>
        internal static string NewProblems {
            get {
                return ResourceManager.GetString("NewProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  no .
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem has no definite cells.
        /// </summary>
        internal static string NoHints {
            get {
                return ResourceManager.GetString("NoHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Problems for printout found.
        /// </summary>
        internal static string NoProblems {
            get {
                return ResourceManager.GetString("NoProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not .
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem is not resolvable!.
        /// </summary>
        internal static string NotResolvable {
            get {
                return ResourceManager.GetString("NotResolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Failed!.
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a number between 1 and {0} in row {1}, column {2}..
        /// </summary>
        internal static string OutOfBounds {
            get {
                return ResourceManager.GetString("OutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Allocations: .
        /// </summary>
        internal static string PreAllocatedValues {
            get {
                return ResourceManager.GetString("PreAllocatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing the Problem is not possible!.
        /// </summary>
        internal static string PrintNotPossible {
            get {
                return ResourceManager.GetString("PrintNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem has\n{0} pre-allocated cells,\n{1} computed cells,\n{2} cells remaning.
        /// </summary>
        internal static string ProblemInfo {
            get {
                return ResourceManager.GetString("ProblemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem solved!.
        /// </summary>
        internal static string ProblemSolved {
            get {
                return ResourceManager.GetString("ProblemSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resources_de_DE {
            get {
                return ResourceManager.GetString("Resources_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Resources_de_DE_Designer {
            get {
                return ResourceManager.GetString("Resources_de_DE_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed!.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save of Problem is not possible!.
        /// </summary>
        internal static string SaveNotPossible {
            get {
                return ResourceManager.GetString("SaveNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution #1.
        /// </summary>
        internal static string SolutionOne {
            get {
                return ResourceManager.GetString("SolutionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution{0} found!.
        /// </summary>
        internal static string SolutionsFound {
            get {
                return ResourceManager.GetString("SolutionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions so far: {0:n0}.
        /// </summary>
        internal static string SolutionsSoFar {
            get {
                return ResourceManager.GetString("SolutionsSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Error.
        /// </summary>
        internal static string SudokuError {
            get {
                return ResourceManager.GetString("SudokuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking....
        /// </summary>
        internal static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time so far: .
        /// </summary>
        internal static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Resolvable!.
        /// </summary>
        internal static string TitleNotResolvable {
            get {
                return ResourceManager.GetString("TitleNotResolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Solutions: .
        /// </summary>
        internal static string TotalNumberOfSolutions {
            get {
                return ResourceManager.GetString("TotalNumberOfSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Solutions so far: .
        /// </summary>
        internal static string TotalNumberOfSolutionsSoFar {
            get {
                return ResourceManager.GetString("TotalNumberOfSolutionsSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivial.
        /// </summary>
        internal static string Trivial {
            get {
                return ResourceManager.GetString("Trivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem is formal valid..
        /// </summary>
        internal static string ValidationStatus {
            get {
                return ResourceManager.GetString("ValidationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
