                <!-- Begin Footer -->
                <table class="FooterTable" style="width:100%">
                    <tr><td class="spacer"></td></tr>
                    <tr>
                    	<td align="left" class="FooterText" style="width:40%"><span class="JustThisApp"><a href="mailto:cp-solutions@arcor.de">Contact</a></span></td>
                        <td align="center" class="FooterText" style="width:20%">
                            <a href="http://www.validome.org/referer">
                                <img alt="Valid XHTML 1.0" height="15" src="http://www.validome.org/images/set4/valid_xhtml_1_0.gif"
                                    style="border:none" width="80"/>
                            </a>
                        </td>
                        <td align="right" class="FooterText" style="width:40%">Last modified: <!--DATE-->2007-01-05<!--/DATE--></td>
                    </tr>
                    <tr><td class="spacer"></td></tr>
                    <tr><td class="spacer" colspan="3" style="width:100%; background-color:#cecece"></td></tr>
                </table>
                <!-- End Footer -->